TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

NORG2_API_V1_URL: https://norg2.dev-fss-pub.nais.io/norg2/api/v1

SAF_BASE_URL: https://saf.dev-fss-pub.nais.io/
SAF_SCOPE: dev-fss.teamdokumenthandtering.saf-q1