TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

SAF_BASE_URL: https://saf.dev-fss-pub.nais.io/
SAF_SCOPE: dev-fss.teamdokumenthandtering.saf-q1

DOK_ARKIV_SCOPE: dev-fss.teamdokumenthandtering.dokarkiv-q1/
DOK_ARKIV_SERVICE_URL: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost

KLAGE_FSS_PROXY_URL: https://klage-fss-proxy.dev-fss-pub.nais.io

FSS_CLUSTER: dev-fss

OPPGAVE_BASE_URL: https://oppgave-q1.dev.intern.nav.no/api/v1/oppgaver
OPPGAVE_SCOPE: dev-fss.oppgavehandtering.oppgave-q1