TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b

SAF_BASE_URL: https://saf.prod-fss-pub.nais.io/
SAF_SCOPE: prod-fss.teamdokumenthandtering.saf

DOK_ARKIV_SCOPE: prod-fss.teamdokumenthandtering.dokarkiv/
DOK_ARKIV_SERVICE_URL: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost

KLAGE_FSS_PROXY_URL: https://klage-fss-proxy.prod-fss-pub.nais.io

FSS_CLUSTER: prod-fss

OPPGAVE_BASE_URL: https://oppgave.intern.nav.no/api/v1/oppgaver
OPPGAVE_SCOPE: prod-fss.oppgavehandtering.oppgave