spring:
  application:
    name: kabin-api
  main:
    banner-mode: OFF
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    log-request-details: true
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: 7083
  error:
    whitelabel:
      enabled: false
  shutdown: graceful

navCallIdName: Nav-Callid

management:
  health:
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    baggage:
      remote-fields:
        - ${navCallIdName}
      correlation:
        fields:
          - ${navCallIdName}
  prometheus:
    metrics:
      export:
        enabled: true

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
  client:
    registration:
      kabal-api-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${NAIS_CLUSTER_NAME}.${NAIS_NAMESPACE}.${KABAL_API_APP_NAME}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      saf-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://${SAF_SCOPE}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

KABAL_API_BASE_URL: http://kabal-api
KABAL_API_APP_NAME: kabal-api